### ISSUE TITLE
List of all e2e test cases we should cover

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#415]
### Epic domain

Below is a list of e2e test scenarios we should be covering when testing bootc extension:

#### Manifest related

- [ ] Build a multi-platform image within Podman Desktop, test that BootC extension sees it
- [ ] Test we can select the manifest and both options are available if we chose amd64 and arm64
- [ ] Test we can build both arm64 AND amd64 (to test cross-arch building)

#### Regular image related
- [ ] Test that non-bootc images do NOT appear
- [ ] Test that our "regular" labelled bootc image appears
- [ ] Test building that above image

#### Disk output testing
- [ ] iso build test
- [ ] raw image test
- [ ] qcow2 image test
- [ ] ami image test
- [ ] vmdk image test

**Comment by odockal** [comment]
@cdrage Do you think that the list of tests to cover can be updated? Anything new we can add since the issue was created?

**Comment by odockal** [comment]
@cbr7 @cdrage I have added some scenario I could think of were added or are missing. Created subissues. Feel free to discuss these and close/update as you wish. If something does not make sense, it is up to you.

**Comment by cdrage** [comment]
> [@cbr7](https://github.com/cbr7) [@cdrage](https://github.com/cdrage) I have added some scenario I could think of were added or are missing. Created subissues. Feel free to discuss these and close/update as you wish. If something does not make sense, it is up to you.

I agree with the new ones!

*Especially* the one testing the RHEL bootc image as well.
