### ISSUE TITLE
Epic: 1-1 CLI to GUI from bootc-image-builder upstream project

### ISSUE THREAD

**Issue by cdrage** [containers/podman-desktop-extension-bootc#474]
### Epic domain

Below is a list of parameters that we have and don't have between the CLI as well as the GUI (this extension).

Keep in mind that this list covers 100% the CLI, but there needs to be discussion whether it's suitable to have each one in bootc extension or not:
- [x] passing in build config https://github.com/containers/podman-desktop-extension-bootc/issues/471
- [x] aws https://github.com/containers/podman-desktop-extension-bootc/issues/139
- [x] chown: https://github.com/containers/podman-desktop-extension-bootc/issues/472
- [x] tls verification: https://github.com/containers/podman-desktop-extension-bootc/issues/473

**Comment by cdrage** [comment]
This has been completed! 🚀 

We are now 1-1 with parameters with bootc-image-builder!
